<?php

function shift_cipher_menu() {
  $items['shift_cipher'] = array(
    'title' => 'Shift Cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['shift_cipher_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'shift_cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('enter a positive value to shift the letters by'),
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );

  $form['shift_direction'] = array(
    '#title' => 'Shift Direction',
    '#type' => 'textfield',
    '#description' => t('Enter a direction to shift the letters.("left" or "right")'),
    '#element_validate' => array('element_validate_left_right'),
    '#required' => TRUE,
  );

  $form['shift_phrase'] = array(
    '#title' => 'Phrase to Shift',
    '#type' => 'textfield',
    '#description' => t("Enter your phrase to shift!"),
    '#element_validate' => array('element_validate_shift_phrase'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Shift!',
  );

  return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
  $shift_value = (int)$form_state['values']['shift_value'];
  $shift_direction = strToLower($form_state['values']['shift_direction']) == 'right' ? 1 : -1;
  $shift_phrase = strToLower($form_state['values']['shift_phrase']);
  $alphabet = range('a', 'z');
  $result_array = array();

  $shift_phrase_array = str_split($shift_phrase);

  foreach($shift_phrase_array as $letter) {
    $shift_letter_index = array_search($letter, $alphabet) + ($shift_value * $shift_direction);
    if ($shift_letter_index > 25) {
      $shift_letter_index = ($shift_letter_index % 26);
    } elseif ($shift_letter_index < 0 && $shift_letter_index >= -25){
      $shift_letter_index += 26;
    } elseif ($shift_letter_index < -25) {
      $shift_letter_index = ($shift_letter_index % 26) * -1;
    }
    if (in_array($letter, $alphabet)) {
      array_push($result_array, $alphabet[$shift_letter_index]);
    } else {
      array_push($result_array, $letter);
    }
  }

  $_SESSION['result'] = implode($result_array);
  $form_state['redirect'] = 'shift_cipher_success_page';

}

function shift_cipher_success() {
  return $_SESSION['result'];
}

// function element_validate_integer_less_than_26($element) {
//   if ($element['#value'] > 26) {
//     form_error($element, t("Value must be a positive integer that is not greater than 26."));
//   }
// }

function element_validate_left_right($element) {
  if (!((strToLower($element['#value'])) == 'right' || (strToLower($element['#value'])) == 'left')) {
    form_error($element, t('You must enter either "right" or "left"!'));
  }
}

function element_validate_shift_phrase($element) {
  if (preg_match('/[^a-zA-Z\s\p{P}]/', $element['#value'])) {
    form_error($element, t('Please only enter letters and punctuation!'));
  }
}
